version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    build:
      context: .
      args:
        env: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    extends:
      file: common.yml
      service: postgres
    volumes_from:
      - pgdata
  pgdata:
    extends:
      file: common.yml
      service: pgdata
volumes:
  pgdata:
