version: '2'
services:
  web:
    extends:
      file: common.yml
      service: web
    image: erickoh/react-starter-kit
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    ports:
      - "8080"
  nginx:
    image: erickoh/nginx
    links:
      - web:web
    ports:
      - "80:80"
  postgres:
    extends:
      file: common.yml
      service: postgres
    volumes_from:
      - pgdata
  pgdata:
    extends:
      file: common.yml
      service: pgdata
volumes:
  pgdata:
